"""Delete stock

Revision ID: 8918b436f362
Revises: 60362259b37c
Create Date: 2026-04-06 19:30:10.176553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8918b436f362'
down_revision: Union[str, Sequence[str], None] = '60362259b37c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stockliststock',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_list_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['stock_list_id'], ['stocklist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stockliststock')
    # ### end Alembic commands ###
