"""fix account

Revision ID: f303ef8dc7ef
Revises: 8918b436f362
Create Date: 2026-06-19 22:53:45.784995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f303ef8dc7ef'
down_revision: Union[str, Sequence[str], None] = '8918b436f362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column(
        'google_id', sa.String(), nullable=True))
    op.alter_column('account', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    op.create_unique_constraint(None, 'account', ['google_id'])
    op.drop_index(op.f('ix_stocklist_id'), table_name='stocklist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_stocklist_id'), 'stocklist', ['id'], unique=False)
    op.drop_constraint(None, 'account', type_='unique')
    op.alter_column('account', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.drop_column('account', 'google_id')
    # ### end Alembic commands ###
