from enum import Enum


class YFinanceInfoKeys(str, Enum):
    SYMBOL = "symbol"
    NAME = "shortName"
    EXCHANGE = "exchange"
    CURRENT_PRICE = "currentPrice"
    PREVIOUS_CLOSE = "previousClose"
    VOLUME = "volume"
    MARKET_CAP = "marketCap"
    PER = "trailingPE"
    PBR = "priceToBook"
    OPERATING_MARGIN = "operatingMargins"
    REVENUE_GROWTH = "revenueGrowth"
    EARNINGS_GROWTH = "earningsGrowth"
    PROFIT_GROWTH = "profitMargins"
    CURRENT_RATIO = "currentRatio"
    DIVIDEND_YIELD = "dividendYield"
    DIVIDEND_PER_SHARE = "dividendRate"
    PAYOUT_RATIO = "payoutRatio"
    FREE_CASH_FLOW = "freeCashflow"
    ROE = "returnOnEquity"
    ROA = "returnOnAssets"
    MARKET = "exchange"
    SECTOR = "sector"
    INDUSTRY = "industry"
